#this is context properties
#Wed Jun 03 23:51:55 ICT 2026
restaurant_db_connection_Port=3306
restaurant_db_connection_Database=restaurant_db
restaurant_db_connection_Login=root
restaurant_db_connection_Password=enc\:routine.encryption.key.v1\:qsYhLSyC6I6WrcIHYZRX8TVTGqSnP1Qnc8DfGmRpCsyJvZtRBg\=\=
restaurant_db_connection_Server=127.0.0.1
restaurant_db_connection_AdditionalParams=noDatetimeStringSync\=true&enabledTLSProtocols\=TLSv1.2,TLSv1.1,TLSv1
